services:
  ponisha-postgres:
    image: postgres:16-alpine
    container_name: ponisha-postgres
    environment:
      POSTGRES_DB: ponisha
      POSTGRES_USER: ponisha
      POSTGRES_PASSWORD: ponisha
    ports:
      - "5433:5432"
    volumes:
      - ponisha_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponisha -d ponisha"]
      interval: 5s
      timeout: 5s
      retries: 10

  ponisha-go-app:
    build:
      context: .
    container_name: ponisha-go-app
    depends_on:
      ponisha-postgres:
        condition: service_healthy
    environment:
      DB_HOST: ponisha-postgres
      DB_PORT: 5432
      DB_USERNAME: ponisha
      DB_PASSWORD: ponisha
      DB_DATABASE: ponisha
      DB_SSLMODE: disable
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      HTTP_PORT: 3000
    ports:
      - "3000:3000"

volumes:
  ponisha_pg_data:
